/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
	public String getGreeting() {
		return "Hello world12345";
	}


	public static void main(String[] args) {
		System.out.println("자바 첫번째 팀프로젝트!");
	}
}
